site_name: My Docs
nav:
  - Home: index.md
  - "Call Kit": "!include ./call_kit/mkdocs.yml"
  - "Video Conference Kit": "!include ./video_conference_kit/mkdocs.yml"
  - "Live Streaming Kit": "!include ./live_streaming_kit/mkdocs.yml"
# theme:
# name: material
# name: readthedocs

# extra:
#   version:
#     provider: mike
plugins:
  - include-markdown
  - search
  # - i18n:
  #     languages:
  #       en:
  #         name: English
  #         build: true
  #         site_name: "My Docs"
  #       zh:
  #         name: 简体中文
  #         build: true
  #         site_name: "中文文档"
  #     default_language: en
  #     nav_translations:
  #       zh:
  #         Start: 开始
  #         About: 关于
  - monorepo
